package nu.hex.asciianimator.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import nu.hex.asciianimator.io.AazFileReader;

/**
 *
 * @author hl
 */
public class MainWindow extends javax.swing.JFrame {

    private static final String START = "Start";
    private static final String PAUSE = "Pause";
    private static final String INFO_TEXT_1 = "Use Open File to load an ASCII Animation file (aaz)";
    private static final String INFO_TEXT_2 = "Click Start to run animation";
    private static final String HELP_TEXT = "Help\n\nThe AAZ Filetype\n"
            + "  The aaz filetype is a zipped archive containing text-files.\n"
            + "The order displayed in the animation is governed by the filenames\n"
            + "in the archive."
            + "";
    private List<String> strings = null;
    private String path;
    private int tenths_of_second = 7;
    private final int tenth_of_second = 100;
    private int currentImage = 0;
    private Timer timer = null;

    public MainWindow() {
        initComponents();
        path = "";
        displayArea.setText(INFO_TEXT_1);
        timer = new Timer(tenths_of_second * tenth_of_second, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                animate();
                togglePrevNextButtons();
                repaint();
            }
        });
    }

    private void animate() {
        if (strings != null && !strings.isEmpty()) {
            if (currentImage == strings.size()) {
                currentImage = 0;
            }
            String image = strings.get(currentImage++);
            updateDisplay(image);
        }
    }

    private static String getStartToolTip() {
        return START + " animation.";
    }

    private static String getStopToolTip() {
        return PAUSE + " animation.";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fileChooserButton = new javax.swing.JButton();
        optionsButton = new javax.swing.JButton();
        startPauseButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        displayScrollPane = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        programLabel.setFont(new java.awt.Font("TlwgTypewriter", 1, 24)); // NOI18N
        programLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        programLabel.setText("ASCII Animator - v 1.0");

        fileChooserButton.setText("Open file");
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });

        optionsButton.setText("Options");
        optionsButton.setEnabled(false);

        startPauseButton.setText(START);
        startPauseButton.setToolTipText(getStartToolTip());
        startPauseButton.setEnabled(false);
        startPauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPauseButtonActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.setEnabled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        prevButton.setText("Prev");
        prevButton.setEnabled(false);
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)
                .addComponent(prevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startPauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileChooserButton)
                    .addComponent(optionsButton)
                    .addComponent(startPauseButton)
                    .addComponent(helpButton)
                    .addComponent(nextButton)
                    .addComponent(stopButton)
                    .addComponent(prevButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        displayArea.setEditable(false);
        displayArea.setColumns(20);
        displayArea.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        displayArea.setRows(5);
        displayScrollPane.setViewportView(displayArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(programLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
        resetContent();
        importFile();
        updateDisplay(INFO_TEXT_2);
        startPauseButton.setEnabled(hasAnimationContent());
        stopButton.setEnabled(hasAnimationContent());
    }//GEN-LAST:event_fileChooserButtonActionPerformed

    private void startPauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPauseButtonActionPerformed
        togglePlayerButtons();
        toggleFileChooserButton();
    }//GEN-LAST:event_startPauseButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        if (displayArea.getText().equals(HELP_TEXT)) {
            if (hasAnimationContent()) {
                updateDisplay(strings.get(currentImage));
            } else {
                updateDisplay(INFO_TEXT_1);
            }
        } else {
            updateDisplay(HELP_TEXT);
            pauseAnimation();
        }
    }//GEN-LAST:event_helpButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        stopAnimation();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        showPreviousImage();
    }//GEN-LAST:event_prevButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        showNextImage();
    }//GEN-LAST:event_nextButtonActionPerformed

    private boolean hasAnimationContent() {
        return strings != null && !strings.isEmpty();
    }

    private void togglePlayerButtons() {
        if (isPlaying()) {
            startPauseButton.setText(START);
            startPauseButton.setToolTipText(getStartToolTip());
            pauseAnimation();
        } else {
            startPauseButton.setText(PAUSE);
            startPauseButton.setToolTipText(getStopToolTip());
            startAnimation();
        }
        togglePrevNextButtons();
    }

    private boolean isPlaying() {
        return startPauseButton.getText().equals(PAUSE);
    }

    private void togglePrevNextButtons() {
        if (isPlaying()) {
            nextButton.setEnabled(false);
            prevButton.setEnabled(false);
        } else {
            nextButton.setEnabled(currentImage < strings.size() - 1);
            prevButton.setEnabled(currentImage > 0);
        }
    }

    private void toggleFileChooserButton() {
        fileChooserButton.setEnabled(startPauseButton.getText().equals(START));
    }

    public void openAnimatorWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea displayArea;
    private javax.swing.JScrollPane displayScrollPane;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton optionsButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JLabel programLabel;
    private javax.swing.JButton startPauseButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables

    private void importFile() {
        try {
            AazFileChooser fileChooser = new AazFileChooser(path, this);
            File file = fileChooser.getFile();
            if (file != null) {
                path = file.getParent();
                strings = new AazFileReader(new FileInputStream(file)).read();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void resetContent() {
        currentImage = 0;
        if (hasAnimationContent()) {
            strings.clear();
        }
    }

    private void updateDisplay(String text) {
        displayArea.setText(text);
        repaint();
    }

    private void showPreviousImage() {
        currentImage = currentImage > 0 ? currentImage - 1 : 0;
        togglePrevNextButtons();
        updateDisplay(strings.get(currentImage));
    }

    private void showNextImage() {
        currentImage = currentImage < strings.size() - 1 ? currentImage + 1 : strings.size() - 1;
        togglePrevNextButtons();
        updateDisplay(strings.get(currentImage));
    }

    private void startAnimation() {
        timer.start();
    }

    private void stopAnimation() {
        timer.stop();
        currentImage = 0;
        updateDisplay(INFO_TEXT_1);
        startPauseButton.setText(START);
        startPauseButton.setToolTipText(getStartToolTip());
        toggleFileChooserButton();
    }

    private void pauseAnimation() {
        timer.stop();
    }
}
